id = "kubernetes"
name = "Kubernetes"
description = "Kubernetes support for Zed."
version = "0.4.0"
schema_version = 1
authors = ["Bart Smykla <bartek@smykla.com>"]
repository = "https://github.com/smykla-skalski/kubernetes-manifests"
snippets = "./snippets/kubernetes.json"

[language_servers.kubernetes-language-server]
name = "Kubernetes Language Server"
languages = ["Kubernetes"]

[language_servers.kubernetes-language-server.language_ids]
"Kubernetes" = "yaml"

[language_servers.helm-language-server]
name = "Helm Language Server"
languages = ["Kubernetes"]

[grammars.yaml]
repository = "https://github.com/zed-industries/tree-sitter-yaml"
commit = "baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"

[context_servers.kubernetes-context-server]

[slash_commands.kubernetes]
description = "Insert a Kubernetes resource manifest template"
requires_argument = true

[slash_commands.kubernetes-explain]
description = "Explain a Kubernetes resource type"
requires_argument = true

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]

[[capabilities]]
kind = "npm:install"
package = "yaml-language-server"
