name: ci

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: stable
  ZED_EXTENSION_CLI_SHA: 03d8e9aee95ea6117d75a48bcac2e19241f6e667

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          targets: wasm32-wasip2
      - uses: taiki-e/install-action@nextest
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo nextest run --workspace --all-targets --no-fail-fast

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          targets: wasm32-wasip2
      - name: Download zed-extension
        run: |
          wget --quiet "https://zed-extension-cli.nyc3.digitaloceanspaces.com/$ZED_EXTENSION_CLI_SHA/x86_64-unknown-linux-gnu/zed-extension"
          chmod +x zed-extension
      - name: Package extension
        run: |
          scratch_dir="$(mktemp -d)"
          output_dir="$(mktemp -d)"
          trap 'rm -rf "$scratch_dir" "$output_dir"' EXIT
          ./zed-extension --source-dir . --scratch-dir "$scratch_dir" --output-dir "$output_dir"
      - name: Download ts_query_ls
        run: |
          wget --quiet https://github.com/ribru17/ts_query_ls/releases/download/v3.15.1/ts_query_ls-x86_64-unknown-linux-gnu.tar.gz
          tar -xf ts_query_ls-x86_64-unknown-linux-gnu.tar.gz
      - name: Check query formatting
        run: ./ts_query_ls format --check .
